// solid-app/src/App.tsx
import type { Component } from 'solid-js';

import logo from './logo.svg';
import styles from './App.module.css';
import MySwitch from './MySwitch';

const App: Component = () => {
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <img src={logo} class={styles.logo} alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          class={styles.link}
          href="https://github.com/solidjs/solid"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Solid
        </a>
        <p>
          <MySwitch />
        </p>
      </header>
    </div>
  );
};

export default App;

// react-app/src/App.tsx
import React from 'react';
import logo from './logo.svg';
import './App.css';
import MySwitch from './MySwitch';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        <p>
          <MySwitch />
        </p>
      </header>
    </div>
  );
}

export default App;
